spring.config.import=optional:file:env.properties

spring.application.name=additi-backend
spring.datasource.hikari.data-source-properties.sslmode=require

spring.datasource.url=jdbc:postgresql://${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudflare:
r2:
account-id: abc123def456
access-key-id: your-access-key
secret-access-key: your-secret-key
bucket-name: additi-products
endpoint: https://abc123def456.r2.cloudflarestorage.com
public-url: https://pub-xxxxx.r2.dev